# general
experiment: 'timmconv_v1'
mode: 'train'
seed: 0
# dataset
label_dir: TRAIN_LABEL_DATASET_PATH
unlabel_dir: TRAIN_UNLABEL_DATASET_PATH
val_dir: VALID_LABEL_DATASET_PATH
n_classes: 41
in_size: 384
batch_size: 32
n_workers: 12
ul_ratio: 5
# model
model: 'timm_convnext'
# train
n_epochs: 10
optimizer: 'sgd'
lr: 0.01
momentum: 0.9
T: 0.5
p_cutoff: 0.5
lambda_u: 1.0
hard_label: False
schduler: 'multistep' # {multistep, False}
amp: True
# ckpt
output_dir: 'output'
tb_dir: 'output_tb'